#!/bin/env python
import json
import subprocess


def new_workspace(index):
    subprocess.call(['swaymsg', 'workspace', 'number', str(index)])


def get_workspaces():
    proc = subprocess.Popen(
        ['swaymsg', '-t', 'get_workspaces'], stdout=subprocess.PIPE)

    out, err = proc.communicate()
    res = json.loads(out)
    return {ws['num']: ws for ws in res}


workspaces = get_workspaces()

for i in range(1, 11):
    # If an empty workspace is currently focussed, do nothing
    if i in workspaces and workspaces[i]['representation'] is None:
        break
    # Otherwise, we open a new workspace at the lowest number
    if i not in workspaces:
        new_workspace(i)
        break
