#!/usr/bin/env python3
import asyncio
import swayipc


async def main():

    workspaces = await swayipc.get_workspaces()
    workspaces = {ws['num']: ws for ws in workspaces}

    for i in range(1, 11):
        # If an empty workspace is currently focussed, do nothing
        if i in workspaces and workspaces[i]['representation'] is None:
            break
        # Otherwise, we open a new workspace at the lowest number
        if i not in workspaces:
            await swayipc.run_command(f'workspace number {i}')
            break


asyncio.run(main())
